name: Auto Releases

on:
  workflow_dispatch:
    inputs:
      force_build:
        description: "Build and upload artifacts even when there's no new commit"
        required: false
        type: boolean
  schedule:
    - cron: "0 0 * * 1"

jobs:

  check:
    outputs:
      should_run: ${{ steps.checker.outputs.should_run }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4.2.2
        with:
          fetch-tags: true
          fetch-depth: 0

      - name: Checkout Celeritas
        run: |
          git clone https://git.taumc.org/embeddedt/celeritas.git

      - name: Get latest hash
        working-directory: ./celeritas
        run: echo "COMMIT_HASH=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: Get previous hash
        run: echo "PREVIOUS_HASH=$(cat ./latest_commit)" >> $GITHUB_ENV

      - name: Debug
        run: |
          echo "latest_hash=${{ env.COMMIT_HASH }}"
          echo "previous_hash=${{ env.PREVIOUS_HASH }}"

      - name: Check if new commits appear
        id: checker
        run: |
          if [[ "${{ env.COMMIT_HASH }}" == "${{ env.PREVIOUS_HASH }}" ]]
          then
            echo "should_run=false" >> $GITHUB_OUTPUT
          else
            echo "should_run=true" >> $GITHUB_OUTPUT
          fi

      - name: Update hash
        if: env.COMMIT_HASH != env.PREVIOUS_HASH
        run: echo $COMMIT_HASH > ./latest_commit

      - name: Commit hash update
        if: env.COMMIT_HASH != env.PREVIOUS_HASH
        uses: EndBug/add-and-commit@v9.1.4
        with:
          add: 'latest_commit'
          push: true

  publish:
    strategy:
      fail-fast: false
      matrix:
        include:
          - version: 1.12.2
          - version: 1.16.5
          - version: 1.20.1
          - version: 1.7.10
          - version: 1.8.9
          - version: 1.21.1
          - version: 1.21.10
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: [check]
    if: (inputs.force_build == true) || (needs.check.outputs.should_run == 'true')
    steps:
      - name: Debug
        run: echo "should_run=${{ needs.check.outputs.should_run }}"

      - name: Checkout this repository
        uses: actions/checkout@v4.2.2
        with:
          fetch-tags: true
          fetch-depth: 0

      - name: Checkout Celeritas
        run: |
          git clone https://git.taumc.org/embeddedt/celeritas.git

      - name: Set up JDK 8 & 17 & 21
        uses: actions/setup-java@v5.0.0
        with:
          java-version: |
              8
              17
              21
          distribution: 'temurin'

      - name: Fix Gradle permission
        run: chmod +x ./celeritas/gradlew

      - name: Build Jars
        working-directory: ./celeritas
        run: ./gradlew -Ptarget_versions=${{ matrix.version }} packageJar

      - uses: actions/upload-artifact@v4
        with:
          name: Artifacts-${{ matrix.version }}
          path: ./celeritas/build/libs

      
